# Generated by Django 3.0.3 on 2020-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutsamplelist',
            name='meta_id',
            field=models.TextField(blank=True),
        ),
    ]
